# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push: # ブランチに関わらずpushされた際に実行する
#    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build -c Release --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Upload EasyConstructor Dll
      uses: actions/upload-artifact@v4
      with:
        name: EasyConstructor.dll
        path: ./EasyConstructor/bin/Release/netstandard2.0/EasyConstructor.dll
    - name: Upload EasyConstructor.SourceGen Dll
      uses: actions/upload-artifact@v4
      with:
        name: EasyConstructor.SourceGen.dll
        path: ./EasyConstructor.SourceGen/bin/Release/netstandard2.0/EasyConstructor.SourceGen.dll
